### ISSUE TITLE
multiple clones (work profiles)

### ISSUE THREAD

**Issue by ka223** [PeterCxy/Shelter#101]
Would be multiple clones from one app possible?

**Comment by jmichael2497** [comment]
please do not abuse the "Issue (for bug reporting)" system as this discourages the developers from regularly reviewing and responding to actual bug report issues.

try reading the entire readme.md for this app first before asking others what it can do (it covers your question).

but also don't forget to spend at least 5 minutes trying a few general web search engines with different keywords, because the chances are pretty good your questions have already been asked and answered somewhere, typically in a general user chat site.

hope that helps, cheers.

**Comment by ka223** [comment]
@jmichael2497 
My question was, if it is possible to implement.
Where should I place a feature request ?

**Comment by jmichael2497** [comment]
just in case this is a misunderstanding, looking again, i see another interpretation of "multiple clones from one app" may be the valid question instead?

i was interpreting that as asking about a feature that the app already does: install random play store app once in main for example, and be able to use that new app in both main and shelter (aka work) profile separately.

were you asking about something else like having more than just main and Shelter (aka work) profile? because i saw something recently about tablets having multi-user profile support code that is not normally part of other devices like phones.

**Comment by ka223** [comment]
Sorry, for the misunderstanding. My intention was to get more than one clone, for example the main app and two clones in shelter. 

I thought, maybe shelter could create more than one work profile, to clone apps.
If one work profile for one user is an android limitation, this is apparently not possible?

**Comment by jmichael2497** [comment]
ah so more than just the one added shelter (work) profile is what you are looking for.

apparently only tablets have code to allow that, according to some discussion on reddit so unfortunately looks like this won't be possible without OS level patches...

but i also saw mention in reddit of problems creating TWRP backups on devices with multiple profiles anyway, so that's why i haven't even tried shelter or island myself.

**Comment by PeterCxy** [comment]
This could be possible using linked user accounts but for now there's no plan to implementing it in Shelter.

**Comment by indolering** [comment]
> This could be possible using linked user accounts but for now there's no plan to implementing it in Shelter.

Could you elaborate a little more on this?  I could *really* use this feature and I would be willing to put some work into making it happen.

**Comment by PeterCxy** [comment]
@indolering unfortunately I'm not really familiar with it. I only know it is possible because Island has had such a feature. I think I have seen some documentation about creating a managed normal user as opposed to a work profile somewhere in Android documentation but I'm not sure where

**Comment by indolering** [comment]
Does island even work anymore?

**Comment by indolering** [comment]
I'm just not finding much documentation on this, so I'm not confident that this is possible.  If you could act as a PM, I would be willing to handle the actual implementation.

**Comment by Akianonymus** [comment]
Recently installed island and found out how it handles multiple profiles.

Actually, you have change some system props.

`persist.sys.max_profiles to 10` whatever the number

and

`ro.debuggable to 1`

After this, you can just create more than one profile and afterwards need to handle the profile same as the other work profile.

This method was told by the Island dev, Oasisfeng.

**Comment by PeterCxy** [comment]
well the fact that it needs ro.debuggable makes it a no for me here. Sorry.

**Comment by Akianonymus** [comment]
@PeterCxy Well, i forgot to mention one thing, you just need ro.debuggable to 1 if you wanna create a work profile. After creating the work profile, it can be changed back. Yes, it's not ideal, but a one time inconvenience.

**Comment by PeterCxy** [comment]
Still nope until this feature gets into the actual public API. Sorry.

**Comment by Osiris-Team** [comment]
@PeterCxy I am working on OpenLauncher and currently implementing work profile support.
I am testing everything on Android 7.0 since multi-user support has existed since then, and It seems that Shelter creates a new user named "Guest".
I simply then get the apps for all available users and add them to the app-drawer which works and looks like this:
![image](https://github.com/PeterCxy/Shelter/assets/59899645/564228e6-7eb2-4432-93d5-b7cbe9c9d2bd)

Problem is that a tester says that on Android 12 this doesn't seem to work anymore. Do you use another logic to create a work profile, for newer Android versions?
