### ISSUE TITLE
[Question] How to activate File Shuttle? 

### ISSUE THREAD

**Issue by auz-jsm** [PeterCxy/Shelter#110]
How to activate the File Shuttle feature of the app? 

_Phone is Nokia 8.1_

![Screenshot_20200128-091916](https://user-images.githubusercontent.com/45415928/73227689-46bb8c80-41af-11ea-8b66-1aef3f79940f.png)

**Comment by rawax** [comment]
Same problem.

Redmi Note 5 (whyred).
AospExtended-v7.0-whyred-20200124-1329-OFFICIAL ( Android 10 )
Shelter 1.5(13) from F-Droid ( tested from play store too )
Storage access granted. Shelter is device admin - checked.
Default file manager - com.google.android.documentsui ( i try other, didn't help )

 [logcat](https://pastebin.com/hPDrX5Dq)

Maybe problem in:
`RenderThread: type=1400 audit(0.0:450): avc: denied { search } for name="kgsl-3d0" dev="sysfs" ino=31023 scontext=u:r:untrusted_app:s0:c190,c256,c512,c768 tcontext=u:object_r:sysfs_kgsl:s0 tclass=dir permissive=1 app=net.typeblog.shelter`

**Comment by Martinius** [comment]
Please see https://github.com/PeterCxy/Shelter/issues/97

FileShutle is intentionally disabled in Android 10 by the author of shelter

**Comment by PeterCxy** [comment]
I will get back to re-implementing this feature once I get my things done for graduation (see #120) and also after Scoped Storage gets actually pinned down by Android 11.

**Comment by oriewancu** [comment]
My alternative way to transfer file between Main and Shelter files:
> Install app **Save To Phone** for both place (Main and Shelter).

> Open app File Manager / Gallery / other similar app from Main or Shelter -> choose the file -> **SHARE** -> choose "**Other Application**" or "**... Work Profile**" -> choose **Save To Phone** -> save to Internal Storage.

It's best way for me and help me a lot. 😇
![IMG-20201010-WA0010](https://user-images.githubusercontent.com/20870841/95658524-400a5500-0b45-11eb-89e3-d05fd798fccf.jpg)
![IMG-20201010-WA0011](https://user-images.githubusercontent.com/20870841/95658533-50223480-0b45-11eb-8cef-971ea33fbd2e.jpg)
![IMG-20201010-WA0012](https://user-images.githubusercontent.com/20870841/95658535-57494280-0b45-11eb-9c7b-daee54f14d81.jpg)

**Comment by otuva** [comment]
To add to the alternative apps here's a FOSS one that works: [phone saver - f-droid](https://f-droid.org/en/packages/link.standen.michael.phonesaver/)

**Comment by CapitalT** [comment]
Phone saver is no longer needed. Shuttle works now, even on an unrooted phone.

**Comment by e-t-l** [comment]
Does Shuttle work both ways? I followed the setup instructions but I can only access my Main files from the Work documents UI, not vice-versa.

**Comment by CapitalT** [comment]
Yes, it should. In my main profile it is called 'Shelter' and in the Sheltered profile 'Main'. Did you give file access permissions to shelter in both profiles?

**Comment by JustMyGithub** [comment]
How does it work? Neither the Stock Samsung Files app nor the Google files app from the store seem to recognize "the other side" after enabling File Shuttle?!

Wouldn't it be useful to allow to copy/move folders within shelter itself, such that a) only selected objects are shared and b) it does not depend on a files app being able to support File Shuttle?!

**Comment by PeterCxy** [comment]
@JustMyGithub There is an option in Shelter's menu called "Open Documents UI". There you will find "the other side". The reason your stock files app or Google files app do not show Shelter is because they are not showing third-party applications by default.

And no, File Shuttle does NOT share "all the files". It is merely an API implementation to allow other apps to ask the user to select files to share via the system Documents UI. And this API is called Storage Access Framework, which ALL apps launched after Android 8 (!!) SHOULD support when requesting the user to select files. The whole purpose is such that the app itself does NOT need to see ALL files on the device.

If you want to conveniently copy files between Shelter and the outside or deal with apps that do not support SAF, use a file manager such as Material Files that can access SAF-based folders. Simply add Shelter as a storage location in its sidebar.

**Comment by JustMyGithub** [comment]
Thx for answering quickly.

I just noticed that F-Droid did not keep Shelter up-to-date (because the device is not rooted). After updating Shelter now I can use "Documents UI", the sidebar shows "Shelter" and I can copy files from work profile to main profile.

> The whole purpose is such that the app itself does NOT need to see ALL files on the device.
When activating File Shuttle, Shelter 1.6 instructed to grant permission to all files on both sides, doesn't that mean that shelter sees all files on the device?! Or is this permission no longer needed after the Shelter update to 1.9?
