### ISSUE TITLE
Notification_Tap, Android10, UI

### ISSUE THREAD

**Issue by 916131** [PeterCxy/Shelter#126]
1: Why do the User need to Tap on the Notification to complete the process of Setting up Work_Profile in Shelter while it is not need in a Closed Source Application named 'Island'.
Island:
https://play.google.com/store/apps/details?id=com.oasisfeng.island&hl=en

2: Please Add Support for Android 10, including Full Compatibility and the Theme/Overlay & Accent System.
3: UI of Shelter seems very Ugly compared to Island Application.
My Apology, if my Writing hurt anyone.

**Comment by PeterCxy** [comment]
> Why do the User need to Tap on the Notification to complete the process of Setting up Work_Profile in Shelter

Because in Android 10 it is no longer possible to bring up an application (in this case, the copy of Shelter inside work profile) without a visible UI. I'm sure there are ways to work around this without user interaction, but I don't really want to bother to implement any of the dirty hacks as they may stop working at any time. A user interaction is always guaranteed to work.

> Please Add Support for Android 10, including Full Compatibility and the Theme/Overlay & Accent System.

Shelter already runs fine on Android 10 except the FileShuttle feature (which due to the incomplete Scoped Storage system, will only be supported again after Android 11). I'm not sure what you are talking about by saying overlay themes, because it's the themes that need to adapt to applications, not applications that need to adapt to themes. You got the order backwards.

> UI of Shelter seems very Ugly compared to Island Application.

I'm not a designer. If you can redesign it for me, I'd be happy to rework the UI code.

**Comment by 916131** [comment]
> > Why do the User need to Tap on the Notification to complete the process of Setting up Work_Profile in Shelter
> 
> Because in Android 10 it is no longer possible to bring up an application (in this case, the copy of Shelter inside work profile) without a visible UI. I'm sure there are ways to work around this without user interaction, but I don't really want to bother to implement any of the dirty hacks as they may stop working at any time. A user interaction is always guaranteed to work.
> 
> > Please Add Support for Android 10, including Full Compatibility and the Theme/Overlay & Accent System.
> 
> Shelter already runs fine on Android 10 except the FileShuttle feature (which due to the incomplete Scoped Storage system, will only be supported again after Android 11). I'm not sure what you are talking about by saying overlay themes, because it's the themes that need to adapt to applications, not applications that need to adapt to themes. You got the order backwards.
> 
> > UI of Shelter seems very Ugly compared to Island Application.
> 
> I'm not a designer. If you can redesign it for me, I'd be happy to rework the UI code.

My Apology for the Theme related Writing, but i did not knew this already, thanking you for telling.
Second, Why don't Shelter request for Root-Access, so that Shelter does everything automatically for Root Users while non-Root Users can Use Shelter without Root-access

**Comment by PeterCxy** [comment]
> Second, Why don't Shelter request for Root-Access, so that Shelter does everything automatically for Root Users while non-Root Users can Use Shelter without Root-access

It is wildly insecure for something like Shelter that covers a lot of stuff to request Root access itself. An exploit may allow other program to utilise Shelter to execute arbitrary privileged operations because of Shelter's complexity. There is nothing preventing you from using Root to do everything that Shelter can't currently do.

**Comment by PeterCxy** [comment]
I am closing this issue because there is no real bug or suggestion.

**Comment by 916131** [comment]
> I am closing this issue because there is no real bug or suggestion.

Okay, and Sorry for Wasting your precious Time if you find my Writing useless...
