### ISSUE TITLE
Add translation for pt_BR

### ISSUE THREAD

**Issue by aevw** [PeterCxy/Shelter#153]
Hi Shelter devs,

Please add translation in pt_BR for Shelter. Here is the file [pt_BR](https://github.com/aevw/RD-pt_BR/blob/master/shelter_strings-pt_BR.xml).

Thanks

**Comment by PeterCxy** [comment]
We have set up a easy-to-use translation UI for Shelter at https://weblate.typeblog.net/projects/shelter/shelter/. If possible, please submit future translations there instead of on GitHub or on the mailing list. I can import your XML file into the UI for editing if you wish so.

**Comment by aevw** [comment]
I didn't know that you were on weblate, it's a good idea to upload these strings there, hope you don't mind doing it... thanks

**Comment by PeterCxy** [comment]
@aevw I have imported your translation to weblate, but there are a few new strings needing translation because Shelter has been updated since this issue was opened. If you would like to maintain the translation, please head over to https://weblate.typeblog.net/projects/shelter/shelter/ to finish up the translation. I'm closing this issue and further translations should all go to the Weblate interface.

**Comment by aevw** [comment]
ok thanks, do you think it'd be possible to allow cross signing with github for weblate

**Comment by PeterCxy** [comment]
what do you mean by cross signing?

**Comment by aevw** [comment]
I guess that the exact name could be different, take a look at screenshot
![signin](https://user-images.githubusercontent.com/69059460/93666184-6fe8a000-fa52-11ea-854a-4463e78ec2fe.png)

**Comment by PeterCxy** [comment]
I'm probably not going to add GitHub sign-in and please kindly note that this project is also migrating off GitHub. I'm still responding to your issue because your issue was opened before I announced the migration plan.
