### ISSUE TITLE
Google pixel 5: hanging on preparing your work profile

### ISSUE THREAD

**Issue by vdboots** [PeterCxy/Shelter#168]
Hi when I open the app the app won’t load  after I configured the work profile. It keeps hanging on preparing in Shelter app

**Comment by PeterCxy** [comment]
Make sure you are not on Do-Not-Disturb mode because you need to click on an notification to finish Shelter setup. I have literally included a warning on the first dialog.

**Comment by PeterCxy** [comment]
Please ignore the previous comment as I may have misunderstood your issue.

There are two possibilities (because you have not stated a detail clearly)

1. If your Shelter gets stuck on the "preparing" page with some fancy animation, then it's most likely an issue with your OS and Shelter can do very little if anything to fix the issue.
2. If, instead, you are stuck on a "Please wait..." dialog with a spinning circle inside Shelter, then the cause is most likely that you are on Do-Not-Disturb mode. Shelter requires you to click on a notification to finish setup, so you have to disable Do-Not-Disturb. (and I have included this warning on the very first dialog).

I am closing this issue anyway because this is most likely not an issue with Shelter.
