### ISSUE TITLE
FYI: Island's FOSS fork - Insular

### ISSUE THREAD

**Issue by proletarius101** [PeterCxy/Shelter#178]
I've forked [Island](https://github.com/oasisfeng/island) as Insular: https://gitlab.com/secure-system/Insular, with:
- all blobs (gms, crashlytics, etc) are removed to comply with F-droid's policy
- Internet access for this app removed because we just don't need it

On F-droid: https://f-droid.org/packages/com.oasisfeng.island.fdroid

Since Shelter isn't that actively maintained, you may try Insular as an alternative to ease your urgent needs, especially on Android 11.
Still, many thanks to PeterCxy!

**Comment by dznsm** [comment]
@proletarius101 don't think its fair to call shelter unmaintained. Had a major update in September (more recently than Island) which targets new features in Android 11 (SDK 30) not sure Island/Insular does yet?

**Comment by dznsm** [comment]
@proletarius101 don't think its fair to say Shelter is unmaintained. It had a major update in September (more recently than Island/Insular) and now targets the latest SDK30 (supports new features available in Android 11).

**Comment by proletarius101** [comment]
Well, it's not **actively** maintained, but still under maintainance. Island is updated last month (see the dev branch https://gitlab.com/secure-system/Insular/-/tree/dev). Insular is even updated this week. It's features are all from Island, though.

Island (and Insular) targets API 29. But it supports file shuttle and cloning split apks even on Android 11.

> supports new features available in Android 11

Not sure what features can be benefited from SDK 30, in the context of Work Profile? (BTW all system built-in work profile updates are _given_ without the need to update the SDK)

**Comment by PeterCxy** [comment]
Shelter targets SDK 30 and most features work fine on Android 11, including File Shuttle and cloning (except that we can't do File Shuttle on Google Play due to policy reasons). Still, I appreciate any work done to make apps FOSS.

Shelter is not very actively maintained at this moment due to personal issues and I don't really have that much resources compared to Island. But I personally use it all the time and will make sure to update Shelter whenever Android API changes / updates. I have some new features and quite a few fixes backlogged and I will get back to it soon.

I will continue to develop Shelter in spite of Island being open-source now and in spite of the FOSS fork (I think I have stated this when Island went OSS). The reason is mainly for fun, and for a different philosophy (and software license) than Island. Also, I have some personal disagreements with the author of Island which I do not really like to talk about here -- and this is part of the reason why I started Shelter in the first place.

I will close this issue because it is not really related to Shelter development, and the GitHub issue list is being deprecated for this project anyway (use the mailing list instead). Also, please avoid linking to Island-related repositories here or in the mailing list, because me seeing Island code could result in licensing issues that I would like to keep clear of.
